#!/bin/bash
# this is a comment
crontab -l | { cat; echo "* * * * * some entry2"; } | crontab -



1 - select * from CUS_View каждые 120 секунд
2 - select * from VVI_View каждые 180 секунд
3 - select code, cat, description, cost, in_service_date, out_service_date from products каждые 60 секунд




exec t2s_exportPos 'No'
exec t2s_exportPRO 'No'
exec t2s_exportVisits

SELECT * FROM jobs
join job_history on job_history.job_id = jobs.command_id
where jobs.operator_id = 1

select * from VVI_View



select top 1000 * from POS_View
select top 1000 * from LOC_View
select top 1000 * from VEQ_View
select top 1000 * from NVE_View


select * from operators
order by id desc
limit 1


/** REQUEST **/
{"Timestamp read from MYSQL":"30.07.2019 12:03:18","timestamp sent to Rabbit":"30.07.2019 12:03:18","Code":{"operatorid":"1","Jobsid":"1","command":"Get Products","software_provider":"vendmax"}}

